/* =============================================================================
   SKEMA Entrepreneurs · Raleigh — Fall 2026
   Single source of truth for the semester. Edit EVENTS and the calendar,
   the "next up" ribbon and the countdown all follow.
   (The downloadable .ics is generated by tools/build-ics.js — re-run it
    after changing dates: `npm run build:ics`)
   ============================================================================= */

const EVENTS = [
  {
    date: '2026-08-25',
    time: '5:30 PM',
    name: 'Launch Night',
    desc: 'Kickoff for the whole campus. A local founder keynotes, the semester calendar is unveiled, and applications open.',
    where: 'Venture II, Room 144',
    ics: { start: '20260825T213000Z', end: '20260825T233000Z' }, // 5:30–7:30 PM EDT
  },
  {
    date: '2026-08-28',
    time: '1:00 – 2:00 PM',
    name: 'Club Meetup',
    desc: 'First working meetup of the semester. Open roles discussed, event planning starts.',
    where: 'Venture II, AI Lab',
    ics: { start: '20260828T170000Z', end: '20260828T180000Z' }, // 1:00–2:00 PM EDT
  },
  {
    date: '2026-09-01',
    time: '11:30 – 12:30',
    name: 'Accelerator Interest Session',
    desc: 'Everything about the 12-week accelerator, answered in the room. Bring the questions you have not asked yet.',
    where: 'Venture II, AI Lab',
    ics: { start: '20260901T153000Z', end: '20260901T163000Z' }, // 11:30–12:30 EDT
  },
  {
    date: '2026-09-22',
    time: 'Time announced soon',
    name: 'Pitch Night',
    desc: 'Campus-wide competition with invited students from partner Raleigh colleges. Local founders judge. Real cash prizes.',
    where: 'Raleigh campus',
    ics: { allDay: true },
  },
  {
    date: '2026-10-27',
    time: 'Time announced soon',
    name: 'Ecosystem Night',
    desc: 'An evening with working founders at Raleigh Founded — walkable from campus. See real early-stage companies operating.',
    where: 'Raleigh Founded',
    ics: { allDay: true },
  },
  {
    date: '2026-11-17',
    time: 'Time announced soon',
    name: 'Demo Day & Showcase',
    desc: 'The capstone. Every accelerator venture presents real traction, streamed live to every SKEMA campus.',
    where: 'Raleigh campus',
    ics: { allDay: true },
  },
];

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const DAYS   = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

/* Parse as local noon so the calendar date never shifts across timezones. */
function parseDate(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(y, m - 1, d, 12, 0, 0);
}

function startOfToday() {
  const n = new Date();
  return new Date(n.getFullYear(), n.getMonth(), n.getDate());
}

/* ---------------------------------------------------------------- calendar */
function renderCalendar() {
  const host = document.getElementById('cal');
  if (!host) return;

  const today = startOfToday();
  const upcoming = EVENTS.filter(e => parseDate(e.date) >= today);
  const nextDate = upcoming.length ? upcoming[0].date : null;

  host.innerHTML = EVENTS.map(e => {
    const d = parseDate(e.date);
    const isDone = d < today;
    const isNext = e.date === nextDate;

    const cls = ['cal-row', isDone ? 'is-done' : '', isNext ? 'is-next' : ''].filter(Boolean).join(' ');
    const pill = isNext
      ? '<span class="pill pill--next">Next up</span>'
      : isDone
        ? '<span class="pill pill--done">Done</span>'
        : '<span class="pill">Upcoming</span>';

    return `
      <div class="${cls}">
        <div class="date">
          <div class="d">${d.getDate()}</div>
          <div class="m">${MONTHS[d.getMonth()]} &middot; ${DAYS[d.getDay()]}</div>
        </div>
        <div class="ev">
          <div class="t">${e.name}</div>
          <div class="d">${e.desc}</div>
        </div>
        <div class="meta"><b>${e.time}</b>${e.where}</div>
        <div class="status">${pill}</div>
      </div>`;
  }).join('');

  return upcoming[0] || null;
}

/* --------------------------------------------------------------- next up */
function renderNextUp(next) {
  const nameEl  = document.getElementById('nextName');
  const whenEl  = document.getElementById('nextWhen');
  const countEl = document.getElementById('nextCount');
  if (!nameEl || !whenEl || !countEl) return;

  if (!next) {
    nameEl.textContent = 'That’s the semester.';
    whenEl.textContent = 'Spring dates announced soon — join the list to get them first.';
    countEl.textContent = '';
    return;
  }

  const d = parseDate(next.date);
  nameEl.textContent = next.name;
  whenEl.textContent = `${DAYS[d.getDay()]}, ${MONTHS[d.getMonth()]} ${d.getDate()} · ${next.time} · ${next.where}`;

  // both anchored at local noon, so the difference is a whole number of days
  const n = new Date();
  const todayNoon = new Date(n.getFullYear(), n.getMonth(), n.getDate(), 12, 0, 0);
  const days = Math.round((d - todayNoon) / 86400000);
  countEl.innerHTML =
    days === 0 ? '<b>Today</b>'
    : days === 1 ? '<b>Tomorrow</b>'
    : `In <b>${days} days</b>`;
}

/* ------------------------------------------------------------------ tabs */
function initTabs() {
  const tabs = Array.from(document.querySelectorAll('.switch [role="tab"]'));
  if (!tabs.length) return;

  function select(key, focus) {
    tabs.forEach(tab => {
      const on = tab.dataset.panel === key;
      tab.setAttribute('aria-selected', String(on));
      const panel = document.getElementById(tab.getAttribute('aria-controls'));
      if (panel) panel.hidden = !on;
      if (on && focus) tab.focus();
    });
  }

  tabs.forEach(tab => tab.addEventListener('click', () => select(tab.dataset.panel)));

  // left/right arrow keys move between tabs, per WAI-ARIA tabs pattern
  tabs.forEach((tab, i) => {
    tab.addEventListener('keydown', ev => {
      if (ev.key !== 'ArrowRight' && ev.key !== 'ArrowLeft') return;
      ev.preventDefault();
      const next = tabs[(i + (ev.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length];
      select(next.dataset.panel, true);
    });
  });

  // any link with data-open="accelerator" jumps to the section AND flips the tab
  document.querySelectorAll('[data-open]').forEach(link => {
    link.addEventListener('click', () => select(link.dataset.open));
  });

  if (location.hash === '#accelerator') select('accelerator');
}

/* ------------------------------------------------------------------ init */
document.addEventListener('DOMContentLoaded', () => {
  renderNextUp(renderCalendar());
  initTabs();
});
